export const STORAGE_KEYS = {
  ACTIVE_LISTS: "ACTIVE_LISTS",
  ARCHIVED_LISTS: "ARCHIVED_LISTS",
  PURCHASE_HISTORY: "PURCHASE_HISTORY",
  SCANNED_HISTORY: "SCANNED_HISTORY",
  STORES_DATA: "STORES_DATA",
};
